// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLZgurfxLONEn8_vbZ_SKaEDprnSouifk',
    appId: '1:308525259663:web:c8495326f851ee0b4bc9fa',
    messagingSenderId: '308525259663',
    projectId: 'chat-app-cc56b',
    authDomain: 'chat-app-cc56b.firebaseapp.com',
    storageBucket: 'chat-app-cc56b.appspot.com',
    measurementId: 'G-N4Z942JVYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3CcB4jncjPkZWvMXxiORvcbeWF6A2UdA',
    appId: '1:308525259663:android:7edb27feae43aa984bc9fa',
    messagingSenderId: '308525259663',
    projectId: 'chat-app-cc56b',
    storageBucket: 'chat-app-cc56b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDntml-59cqnW_hBUNSegfTQfc4V2f9PBY',
    appId: '1:308525259663:ios:c94cf50a48cc5b314bc9fa',
    messagingSenderId: '308525259663',
    projectId: 'chat-app-cc56b',
    storageBucket: 'chat-app-cc56b.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDntml-59cqnW_hBUNSegfTQfc4V2f9PBY',
    appId: '1:308525259663:ios:78f153e9038a62874bc9fa',
    messagingSenderId: '308525259663',
    projectId: 'chat-app-cc56b',
    storageBucket: 'chat-app-cc56b.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
